"""Lean 4 versions of the certificate checks.

For each problem with a built-in checker, ``render`` writes a self-contained
Lean 4 file (core Lean, no Mathlib) that defines the problem's combinatorial
property, states the submitted certificate as data, and asks Lean to prove
``certificate_valid : valid … = true``. Small certificates are proved by the
kernel (``decide +kernel``); large ones by ``native_decide``, which also trusts
Lean's compiler. ``#print axioms`` makes the difference visible.

Lean checks the certificate itself: for example, that 150 grid points contain
no three collinear. The headline bound it implies (a Shannon-capacity bound,
a square-difference exponent) follows from a classical theorem that is cited,
not formalized here.

Shared with the community hub, which runs these files on GitHub Actions.
"""

from __future__ import annotations

import json
import re

LEAN_TOOLCHAIN = "leanprover/lean4:v4.34.1"
KERNEL_WORK_LIMIT = 1_500_000  # about two minutes of kernel reduction

HEADER = """-- Generated by Math@Home. Checks one certificate against the problem's definition.
set_option maxRecDepth 100000
set_option maxHeartbeats 0
"""

NO_THREE = """namespace MathAtHome.NoThreeInLine

/-- A point lies on the n × n grid, coordinates 1…n. -/
def inGrid (n : Nat) (p : Nat × Nat) : Bool :=
  1 ≤ p.1 && p.1 ≤ n && 1 ≤ p.2 && p.2 ≤ n

/-- Three points lie on one straight line (their cross product is zero). -/
def collinear (a b c : Nat × Nat) : Bool :=
  ((b.1 : Int) - a.1) * ((c.2 : Int) - a.2) == ((c.1 : Int) - a.1) * ((b.2 : Int) - a.2)

def noneCollinearWith (a : Nat × Nat) : List (Nat × Nat) → Bool
  | [] => true
  | b :: rest => rest.all (fun c => !collinear a b c) && noneCollinearWith a rest

/-- No three of the points are collinear. -/
def noThreeCollinear : List (Nat × Nat) → Bool
  | [] => true
  | a :: rest => noneCollinearWith a rest && noThreeCollinear rest

/-- 2n distinct points of the n × n grid, no three collinear. -/
def valid (n : Nat) (ps : List (Nat × Nat)) : Bool :=
  ps.length == 2 * n && ps.all (inGrid n) && ps.eraseDups.length == ps.length && noThreeCollinear ps

def n : Nat := {n}

def points : List (Nat × Nat) := {points}

theorem certificate_valid : valid n points = true := by {tactic}

#print axioms certificate_valid

end MathAtHome.NoThreeInLine
"""

SHANNON = """namespace MathAtHome.ShannonC7

/-- Two symbols of the 7-cycle are equal or neighbours. -/
def close (a b : Nat) : Bool :=
  let d := (a + 7 - b) % 7
  d == 0 || d == 1 || d == 6

/-- Two words are confusable when every position is close (the strong product). -/
def confusable (u v : List Nat) : Bool :=
  (u.zip v).all (fun p => close p.1 p.2)

/-- No two different words in the list are confusable. -/
def independent : List (List Nat) → Bool
  | [] => true
  | w :: rest => rest.all (fun v => !confusable w v) && independent rest

/-- Distinct words of length k over 0…6, pairwise non-confusable:
an independent set in the k-th strong power of C₇. -/
def valid (k : Nat) (ws : List (List Nat)) : Bool :=
  ws.all (fun w => w.length == k && w.all (· < 7)) && ws.eraseDups.length == ws.length && independent ws

def k : Nat := {k}

def words : List (List Nat) := {words}

theorem certificate_valid : valid k words = true := by {tactic}

theorem certificate_size : words.length = {size} := by decide

#print axioms certificate_valid

end MathAtHome.ShannonC7
"""

SQUARE_DIFFERENCE = """namespace MathAtHome.SquareDifference

/-- m has no square factor above 1. -/
def squareFree (m : Nat) : Bool :=
  (List.range (m + 1)).all (fun d => d < 2 || d * d > m || m % (d * d) != 0)

/-- x is a square modulo m. -/
def isSquareMod (m x : Nat) : Bool :=
  (List.range m).any (fun y => y * y % m == x)

/-- A square-free modulus and at least two distinct residues, no two of which
differ (in either order) by a square modulo m: Ruzsa's construction input. -/
def valid (m : Nat) (rs : List Nat) : Bool :=
  2 ≤ m && squareFree m && 2 ≤ rs.length && rs.all (· < m) && rs.eraseDups.length == rs.length &&
  rs.all (fun r => rs.all (fun s => r == s || !isSquareMod m ((r + m - s) % m)))

def m : Nat := {m}

def residues : List Nat := {residues}

theorem certificate_valid : valid m residues = true := by {tactic}

#print axioms certificate_valid

end MathAtHome.SquareDifference
"""

STATEMENTS = {
  "no_three_in_line": "the {count} points lie on the {n} × {n} grid, are distinct, number exactly 2n, and contain no three on one line",
  "c7_independent_set": "the {count} words of length {k} over 0–6 are distinct and pairwise non-confusable, an independent set in the {k}-th strong power of C₇",
  "square_difference_modulus": "{m} is square-free and no two of the {count} residues differ by a square modulo {m}",
}
CONSEQUENCES = {
  "no_three_in_line": "That is exactly the definition of a solution for this grid size; nothing else is assumed.",
  "c7_independent_set": "The bound Θ(C₇) ≥ N^(1/k) then follows from the definition of the Shannon capacity (not formalized here).",
  "square_difference_modulus": "The exponent ½(1 + log|R| / log m) then follows from Ruzsa's 1984 construction (not formalized here).",
}


def _lean_pairs(points) -> str:
  return "[" + ", ".join(f"({int(x)}, {int(y)})" for x, y in points) + "]"


def _lean_nested(words) -> str:
  return "[" + ", ".join("[" + ", ".join(str(int(s)) for s in w) + "]" for w in words) + "]"


def _lean_list(values) -> str:
  return "[" + ", ".join(str(int(v)) for v in values) + "]"


def _tactic(work: int, prefer_native: bool = False) -> str:
  return "native_decide" if prefer_native or work > KERNEL_WORK_LIMIT else "decide +kernel"


def render(kind: str, certificate: dict, prefer_native: bool = False) -> dict | None:
  """The Lean file for a certificate, or None when no Lean check exists for it.

  Inputs are validated as plain integers before they reach the file, so a
  certificate can never inject Lean code.
  """
  if not isinstance(certificate, dict):
    return None
  try:
    if kind == "no_three_in_line":
      n = int(certificate["n"])
      points = [(int(p[0]), int(p[1])) for p in certificate["points"]]
      if not (2 <= n <= 400) or not all(len(p) == 2 for p in certificate["points"]):
        return None
      work = len(points) ** 3 // 6
      source = NO_THREE.format(n=n, points=_lean_pairs(points), tactic=_tactic(work, prefer_native))
      facts = {"count": len(points), "n": n}
    elif kind == "c7_independent_set":
      k = int(certificate["power"])
      words = [[int(s) for s in w] for w in certificate["words"]]
      if not (1 <= k <= 8) or not words:
        return None
      work = len(words) ** 2 * k // 2
      source = SHANNON.format(k=k, words=_lean_nested(words), size=len(words), tactic=_tactic(work, prefer_native))
      facts = {"count": len(words), "k": k}
    elif kind == "square_difference_modulus":
      m = int(certificate["modulus"])
      residues = [int(r) for r in certificate["residues"]]
      if not (2 <= m <= 2_000_000) or len(residues) < 2:
        return None
      work = len(residues) ** 2 * m + m
      source = SQUARE_DIFFERENCE.format(m=m, residues=_lean_list(residues), tactic=_tactic(work, prefer_native))
      facts = {"count": len(residues), "m": m}
    else:
      return None
  except (KeyError, TypeError, ValueError, IndexError):
    return None
  method = "kernel" if "decide +kernel" in source else "native"
  return {
    "source": HEADER + source,
    "method": method,
    "toolchain": LEAN_TOOLCHAIN,
    "statement": STATEMENTS[kind].format(**facts),
    "consequence": CONSEQUENCES[kind],
  }


AXIOM_LINE = re.compile(r"depends on axioms: \[([^\]]*)\]")


def interpret(returncode: int, output: str, method: str) -> dict:
  """Turn a Lean run into a verification record."""
  if returncode != 0:
    first_error = next((line for line in output.splitlines() if "error" in line.lower()), output.strip()[:200])
    first_error = re.sub(r"^\S*/([^/\s]+\.lean)", r"\1", first_error)  # no local paths
    return {"status": "failed", "method": method, "detail": first_error[:300]}
  match = AXIOM_LINE.search(output)
  axioms = [a.strip() for a in match.group(1).split(",") if a.strip()] if match else []
  if "sorryAx" in axioms:
    return {"status": "failed", "method": method, "detail": "The proof uses sorry.", "axioms": axioms}
  return {"status": "verified", "method": method, "axioms": axioms}


def summary(record: dict | None) -> str:
  """One line for people, e.g. 'Lean 4 ✓ (kernel)'."""
  if not isinstance(record, dict):
    return "Lean 4: not run"
  if record.get("status") == "verified":
    return "Lean 4 ✓ (kernel)" if record.get("method") == "kernel" else "Lean 4 ✓ (compiled check)"
  if record.get("status") == "failed":
    return "Lean 4 ✗"
  return "Lean 4: not run"


def dumps(record: dict) -> str:
  return json.dumps(record, ensure_ascii=False, sort_keys=True)
